trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
# show the below command output so we can have info about how this looks like on more recent macOS versions on CI
- script: xcodebuild -version -sdk
  displayName: 'Show xcodebuild versions'
  
- script: curl -L https://api.nest.saker.build/bundle/download/saker.build-v$(curl -s https://mirror.nest.saker.build/badges/saker.build/latest.txt) -o saker.build.jar
  displayName: 'Download saker.build'
- script: java -jar saker.build.jar -bd build -trace pwd://build/build_export.trace -trace-artifacts-embed export
  displayName: 'Export'

- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish export trace'
  inputs:
    pathtoPublish: build/build_export.trace
    artifactName: export_trace
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish export JARs'
  inputs:
    pathtoPublish: build/saker.jar.create/
    artifactName: export_jars

- script: java -jar saker.build.jar -bd build -trace pwd://build/build_test.trace test_internals
  displayName: 'Test'
- task: PublishBuildArtifacts@1
  condition: always()
  displayName: 'Publish test trace'
  inputs:
    pathtoPublish: build/build_test.trace
    artifactName: trace
